CREATE TABLE IF NOT EXISTS cases (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	case_name VARCHAR(50) NOT NULL,
	customer_id INT NOT NULL,
	case_date DATE NOT NULL DEFAULT (curdate()),
	shipping_status TINYINT NULL DEFAULT '0' COMMENT '0.データ無し 1.支払待ち 2.発送待ち 3.発送済み 4.キャンセル',
	memo TEXT NULL DEFAULT NULL,
	shipping_stock_flg TINYINT NOT NULL DEFAULT '0' COMMENT '0.未発送 1.発送済み',
	is_deleted TINYINT NOT NULL DEFAULT '0' COMMENT '0.未削除　1.削除済',
	create_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	update_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customer (
	id INT NOT NULL AUTO_INCREMENT,
	last_name VARCHAR(50) NOT NULL,
	first_name VARCHAR(50) NOT NULL,
	zipcode VARCHAR(50) NOT NULL,
	address VARCHAR(255) NOT NULL,
	phone_number VARCHAR(50) NOT NULL,
	memo TEXT NULL DEFAULT NULL,
	is_deleted TINYINT NOT NULL DEFAULT '0' COMMENT '0.未削除　1.削除済',
	create_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	update_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS department (
	id INT NOT NULL AUTO_INCREMENT,
	department_name VARCHAR(50) NOT NULL,
	code INT NOT NULL DEFAULT '0',
	create_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	update_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP
)
;

CREATE TABLE IF NOT EXISTS inquiry (
	id INT NOT NULL AUTO_INCREMENT,
	case_id INT NOT NULL,
	inquiry_date DATE NOT NULL DEFAULT (curdate()),
	contents TEXT NOT NULL,
	is_deleted TINYINT NOT NULL DEFAULT '0' COMMENT '0.未削除　1.削除済',
	create_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	update_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
	id INT NOT NULL AUTO_INCREMENT,
	case_id INT NOT NULL,
	order_date DATE NOT NULL DEFAULT (curdate()),
	memo TEXT NULL DEFAULT NULL,
	is_deleted TINYINT NOT NULL DEFAULT '0' COMMENT '0.未削除　1.削除済',
	create_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	update_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_product (
	id INT NOT NULL AUTO_INCREMENT,
	orders_id INT NOT NULL,
	product_id INT NOT NULL,
	quantity INT NOT NULL,
	discount INT NULL DEFAULT NULL,
	is_deleted TINYINT NOT NULL DEFAULT '0' COMMENT '0.未削除　1.削除済',
	create_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	update_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product (
	id INT NOT NULL AUTO_INCREMENT,
	product_name VARCHAR(50) NOT NULL,
	product_category_id INT NOT NULL,
	price INT NOT NULL,
	stock INT NOT NULL,
	is_choose TINYINT NOT NULL DEFAULT '0' COMMENT '0.登録可　1.登録不可',
	create_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	update_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_category (
	id INT NOT NULL AUTO_INCREMENT,
	category_name VARCHAR(50) NOT NULL,
	create_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	update_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quotation (
	id INT NOT NULL AUTO_INCREMENT,
	case_id INT NOT NULL,
	quotation_date DATE NOT NULL DEFAULT (curdate()),
	memo TEXT NULL DEFAULT NULL,
	is_deleted TINYINT NOT NULL DEFAULT '0' COMMENT '0.未削除　1.削除済',
	create_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	update_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quotation_product (
	id INT NOT NULL AUTO_INCREMENT,
	quotation_id INT NOT NULL,
	product_id INT NOT NULL,
	quantity INT NOT NULL,
	discount INT NULL DEFAULT NULL,
	is_deleted TINYINT NOT NULL DEFAULT '0' COMMENT '0.未削除　1.削除済',
	create_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	update_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
	id INT NOT NULL AUTO_INCREMENT,
	role_name VARCHAR(50) NOT NULL,
	create_date_time DATETIME NOT NULL DEFAULT (now()),
	update_date_time DATETIME NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
	id INT NOT NULL AUTO_INCREMENT,
	user_id VARCHAR(50) NOT NULL,
	password VARCHAR(255) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	first_name VARCHAR(50) NOT NULL,
	email_address VARCHAR(255) NOT NULL,
	department_id INT NOT NULL,
	role INT NOT NULL,
	is_deleted TINYINT NOT NULL DEFAULT '0' COMMENT '0.未削除　1.削除済',
	create_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	update_date_time DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP
);